### PR TITLE
Continue Anyways update

### PR DESCRIPTION
**Pull request by jonkootje**
- Added "Continue Anyways" feature to blocked.html.

---

System works with get variable in the url. When redirecting to blocked.html the blocked url comes with it. When the user clicks on continue anyways, the page will redirect to the url with an extra get variable in the url (continuehexi=true). This is how the extension knows, the user wants to continue, and the extension wont block the page.

### CODE REVIEW

**Comment by Gilbert142** [comment]
2 things:
1. Extensions can't execute js code in html files, use external scripts instead
2. The 'continue anyways' button doesn't seem to redirect to anywhere?

**Comment by Gilbert142** [comment]
I'll take the code you made and make it compatible with weird chrome extension-thingies

**Comment by jonkootje** [comment]
Eeehm did i put code in an html file? Thats only in test.html i think and that file is not required, i forgot tod delete the file. I've tested te extension now and it all worked here.

**Comment by jonkootje** [comment]
Wait... a lot of files are missing in the pull request

**Pull request merged**
